image: cirrusci/flutter:stable

stages:
- build
- test
- analyze

before_script:
- cd $TARGET
- flutter pub get
- flutter clean

mobile:
  stage: build
  variables:
    TARGET: "example"
  script:
  - flutter build apk
  tags:
  - shared
  only:
  - dev

web:
  stage: build
  variables:
    TARGET: "example"
  script:
  - flutter build web
  tags:
  - shared
  only:
  - dev


desktop:
  stage: build
  variables:
    TARGET: "example"
  script:
  - apt-get update --yes
  - apt-get install --yes cmake
  - apt-get install --yes ninja-build
  - apt-get install --yes clang
  - flutter config --enable-linux-desktop
  - flutter doctor -v
  - flutter build linux
  tags:
  - shared
  only:
  - dev

platform_test:
  stage: test
  variables:
    TARGET: "example"
  script:
  - flutter test
  tags:
  - shared
  only:
  - dev

unit_test:
  stage: test
  variables:
    TARGET: "themes"
  script:
  - flutter test test/*
  tags:
  - shared
  only:
  - merge_requests

analyze:
  stage: analyze

  variables:
    TARGET: "themes"
  script:
  - flutter analyze
  tags:
  - shared
  only:
  - merge_requests
