image: ghcr.io/cirruslabs/flutter

stages:
- build
- test
- analyze

before_script:
- cd $TARGET
- flutter pub get
- flutter clean

mobile:
  stage: build
  variables:
    TARGET: "example"
  script:
  - flutter build apk
  tags:
  - saas-linux-small-amd64
  only:
    changes:
    - example/*
    - ./*

web:
  stage: build
  variables:
    TARGET: "example"
  script:
  - flutter build web
  tags:
  - saas-linux-small-amd64
  only:
    changes:
    - example/*
    - ./*


desktop:
  stage: build
  variables:
    TARGET: "example"
  script:
  - apt-get update --yes
  - apt-get install --yes cmake ninja-build clang pkg-config libgtk-3-dev libblkid-dev liblzma-dev
  - flutter config --enable-linux-desktop
  - flutter build linux
  tags:
  - saas-linux-small-amd64
  only:
    changes:
    - example/*
    - ./*

platform_test:
  stage: test
  variables:
    TARGET: "example"
  script:
  - flutter test
  tags:
  - saas-linux-small-amd64
  only:
    changes:
    - example/*
    - ./*

unit_test:
  stage: test
  variables:
    TARGET: "."
  script:
  - flutter test --coverage ./lib
  - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info --ignore-errors unused
  - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    paths:
    - coverage
  tags:
  - saas-linux-small-amd64
  only:
  - merge_requests
  - dev
  - main

analyze:
  stage: analyze

  variables:
    TARGET: "."
  script:
  - flutter analyze
  tags:
  - saas-linux-small-amd64
  only:
  - merge_requests
