image: cirrusci/flutter:stable

stages:
- build
- test
- analyze

before_script:
- cd $TARGET
- flutter pub get
- flutter clean

mobile:
  stage: build
  variables:
    TARGET: "example"
  script:
  - flutter build apk
  tags:
  - shared
  only:
  - dev

web:
  stage: build
  variables:
    TARGET: "example"
  script:
  - flutter build web
  tags:
  - shared
  only:
  - dev
  - master


desktop:
  stage: build
  variables:
    TARGET: "example"
  script:
  - apt-get update --yes
  - apt-get install --yes cmake ninja-build clang pkg-config libgtk-3-dev libblkid-dev liblzma-dev
  - flutter config --enable-linux-desktop
  - flutter doctor -v
  - flutter build linux
  tags:
  - shared
  only:
  - dev
  - master

platform_test:
  stage: test
  variables:
    TARGET: "example"
  script:
  - flutter test
  tags:
  - shared
  only:
  - dev
  - master

unit_test:
  stage: test
  variables:
    TARGET: "themes"
  script:
  - flutter test
  - lcov --list coverage/lcov.info
  - genhtml coverage/lcov.info --output=coverage
  artifacts:
    paths:
    - coverage
  tags:
  - shared
  only:
  - merge_requests
  - master

analyze:
  stage: analyze

  variables:
    TARGET: "themes"
  script:
  - flutter analyze
  tags:
  - shared
  only:
  - merge_requests
