// Generates web/quarto/wabisabi-light.scss and wabisabi-dark.scss from Dart tokens.
// Run: dart tool/export_tokens.dart
// CI checks for drift: dart tool/export_tokens.dart && git diff --exit-code web/quarto/
//
// The token imports are relative on purpose: this runs under bare `dart` in CI
// with no package resolution, which is the whole reason tokens/*_raw.dart carry
// no Flutter dependency.
// ignore_for_file: avoid_relative_lib_imports

import 'dart:io';
import '../lib/tokens/palette_raw.dart';
import '../lib/tokens/spacing_raw.dart';

String hex(int argb) {
  final r = (argb >> 16) & 0xFF;
  final g = (argb >> 8) & 0xFF;
  final b = argb & 0xFF;
  return '#'
      '${r.toRadixString(16).padLeft(2, '0')}'
      '${g.toRadixString(16).padLeft(2, '0')}'
      '${b.toRadixString(16).padLeft(2, '0')}';
}

String scssFile({
  required String variant,
  required int background,
  required int surface,
  required int primary,
  required int secondary,
  required int accent,
  required int onColor,
  required int text,
  required int woody,
}) => '''
// wabisabi $variant theme — generated by tool/export_tokens.dart
// DO NOT EDIT — change lib/tokens/*_raw.dart and re-run the tool.

/*-- scss:defaults --*/

// Bootstrap variable overrides
\$body-bg:           ${hex(background)};
\$body-color:        ${hex(text)};
\$primary:           ${hex(woody)};
\$secondary:         ${hex(secondary)};
\$success:           ${hex(onColor)};
\$link-color:        ${hex(accent)};
\$card-bg:           ${hex(surface)};
\$navbar-bg:         ${hex(surface)};
\$border-radius:     ${kCardBorderRadius.toStringAsFixed(0)}px;
\$border-radius-lg:  ${(kCardBorderRadius * 1.5).toStringAsFixed(0)}px;
\$border-radius-sm:  ${(kCardBorderRadius * 0.5).toStringAsFixed(0)}px;
\$container-max-widths: (sm: 540px, md: 720px, lg: ${kContentMaxWidth.toStringAsFixed(0)}px, xl: ${kContentMaxWidth.toStringAsFixed(0)}px, xxl: ${kContentMaxWidth.toStringAsFixed(0)}px);

/*-- scss:rules --*/

// CSS custom properties — full wabi-sabi palette
:root {
  // Named palette
  --wab-clay:      ${hex(kClay)};
  --wab-stone:     ${hex(kStone)};
  --wab-bamboo:    ${hex(kBamboo)};
  --wab-elm:       ${hex(kElm)};
  --wab-moss:      ${hex(kMoss)};
  --wab-rust:      ${hex(kRust)};
  --wab-indigo:    ${hex(kIndigoDye)};
  --wab-pebble:    ${hex(kPebble)};
  --wab-rice:      ${hex(kRice)};
  --wab-ash:       ${hex(kAsh)};
  --wab-charcoal:  ${hex(kCharcoal)};
  --wab-soil:      ${hex(kSoil)};
  --wab-sakura:    ${hex(kSakura)};
  --wab-maple:     ${hex(kMaple)};
  --wab-persimmon: ${hex(kPersimmon)};
  --wab-tea:       ${hex(kTea)};
  --wab-paper:     ${hex(kPaper)};
  --wab-cedar:     ${hex(kCedar)};
  --wab-ceramic:   ${hex(kCeramic)};
  --wab-sand:      ${hex(kSand)};

  // Semantic $variant roles
  --wab-background: ${hex(background)};
  --wab-surface:    ${hex(surface)};
  --wab-primary:    ${hex(primary)};
  --wab-secondary:  ${hex(secondary)};
  --wab-accent:     ${hex(accent)};
  --wab-on:         ${hex(onColor)};
  --wab-text:       ${hex(text)};
  --wab-woody:      ${hex(woody)};

  // Spacing
  --wab-radius:        ${kCardBorderRadius.toStringAsFixed(0)}px;
  --wab-max-width:     ${kContentMaxWidth.toStringAsFixed(0)}px;
  --wab-padding:       ${kPaddingAll.toStringAsFixed(0)}px;
  --wab-padding-h:     ${kPaddingContainerSmallH.toStringAsFixed(0)}px;
  --wab-padding-v:     ${kPaddingContainerSmallV.toStringAsFixed(0)}px;
}
''';

void main() {
  final outDir = Directory('web/quarto');
  if (!outDir.existsSync()) outDir.createSync(recursive: true);

  File('web/quarto/wabisabi-light.scss').writeAsStringSync(scssFile(
    variant:    'light',
    background: kLightBackground,
    surface:    kLightSurface,
    primary:    kLightPrimary,
    secondary:  kLightSecondary,
    accent:     kLightAccent,
    onColor:    kLightOn,
    text:       kLightText,
    woody:      kLightWoody,
  ));

  File('web/quarto/wabisabi-dark.scss').writeAsStringSync(scssFile(
    variant:    'dark',
    background: kDarkBackground,
    surface:    kDarkSurface,
    primary:    kDarkPrimary,
    secondary:  kDarkSecondary,
    accent:     kDarkAccent,
    onColor:    kDarkOn,
    text:       kDarkText,
    woody:      kDarkWoody,
  ));

  stdout.writeln('✓ web/quarto/wabisabi-light.scss');
  stdout.writeln('✓ web/quarto/wabisabi-dark.scss');
}
